stages:
  - publish

npm-publish:
  stage: publish
  image: node:6
  script:
    - echo "$NPM_AUTH" >> ~/.npmrc
    - echo "unsafe-perm=true" >> ~/.npmrc
    - npm publish
  only:
    - tags
  tags:
    - docker
